default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: rankingXD_development

test:
  <<: *default
  database: rankingXD_test


production:
  <<: *default
  database: rankingXD_production
  username: rankingXD
  password: <%= ENV['RANKINGXD_DATABASE_PASSWORD'] %>